# Generated by Django 3.1.1 on 2020-09-12 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.TextField(max_length=364)),
                ('answer2', models.TextField(max_length=364)),
                ('answer3', models.TextField(max_length=364)),
                ('answer4', models.TextField(max_length=364)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerList2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.TextField(max_length=364)),
                ('answer2', models.TextField(max_length=364)),
                ('answer3', models.TextField(max_length=364)),
                ('answer4', models.TextField(max_length=364)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAnswer', models.TextField(max_length=364)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectAnswer2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAnswer2', models.TextField(max_length=364)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=364)),
                ('question2', models.TextField(max_length=364, null=True)),
                ('answerList', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answerlist')),
                ('answerList2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answerlist2')),
            ],
        ),
        migrations.AddField(
            model_name='answerlist2',
            name='correctAnswer2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.correctanswer2'),
        ),
        migrations.AddField(
            model_name='answerlist',
            name='correctAnswer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.correctanswer'),
        ),
    ]
