# Generated by Django 3.1.1 on 2020-09-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200914_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlist',
            name='answer1',
            field=models.TextField(blank=True, max_length=364, null=True),
        ),
        migrations.AlterField(
            model_name='answerlist',
            name='answer2',
            field=models.TextField(blank=True, max_length=364, null=True),
        ),
        migrations.AlterField(
            model_name='answerlist',
            name='answer3',
            field=models.TextField(blank=True, max_length=364, null=True),
        ),
        migrations.AlterField(
            model_name='answerlist',
            name='answer4',
            field=models.TextField(blank=True, max_length=364, null=True),
        ),
        migrations.AlterField(
            model_name='answerlist2',
            name='answer1',
            field=models.TextField(blank=True, max_length=364, null=True),
        ),
        migrations.AlterField(
            model_name='answerlist2',
            name='answer2',
            field=models.TextField(blank=True, max_length=364, null=True),
        ),
        migrations.AlterField(
            model_name='answerlist2',
            name='answer3',
            field=models.TextField(blank=True, max_length=364, null=True),
        ),
        migrations.AlterField(
            model_name='answerlist2',
            name='answer4',
            field=models.TextField(blank=True, max_length=364, null=True),
        ),
    ]
