# Generated by Django 3.1.1 on 2020-09-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200914_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='correctAnswer',
            field=models.TextField(max_length=364, null=True),
        ),
        migrations.AlterField(
            model_name='correctanswer2',
            name='correctAnswer2',
            field=models.TextField(max_length=364, null=True),
        ),
    ]
