# Generated by Django 3.1.1 on 2020-09-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200914_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='correctAnswer',
            field=models.TextField(blank=True, max_length=364, null=True),
        ),
        migrations.AlterField(
            model_name='correctanswer2',
            name='correctAnswer2',
            field=models.TextField(blank=True, max_length=364, null=True),
        ),
    ]
