# Generated by Django 3.1.1 on 2020-09-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200914_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.BooleanField(default=False)),
                ('question2', models.BooleanField(default=False)),
                ('question3', models.BooleanField(default=False)),
                ('question4', models.BooleanField(default=False)),
                ('question5', models.BooleanField(default=False)),
                ('question6', models.BooleanField(default=False)),
                ('question7', models.BooleanField(default=False)),
                ('question8', models.BooleanField(default=False)),
                ('question9', models.BooleanField(default=False)),
                ('question10', models.BooleanField(default=False)),
            ],
        ),
    ]
