# Generated by Django 3.1.1 on 2020-09-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_quizresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeResponseAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeResponseAnswer', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionAnswer', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='question10',
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='question5',
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='question6',
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='question7',
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='question8',
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='question9',
        ),
        migrations.AddField(
            model_name='quizresults',
            name='answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.questionanswer'),
        ),
    ]
