# Generated by Django 3.1.1 on 2020-09-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200918_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeResponseAnswer',
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='answer',
        ),
        migrations.AddField(
            model_name='quizresults',
            name='questionAnswer',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
