# Generated by Django 3.1.1 on 2020-09-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200919_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresults',
            name='question2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizresults',
            name='question3',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
