# Generated by Django 3.1.1 on 2020-09-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200921_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresults',
            name='question4',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
