# Generated by Django 3.1.1 on 2020-09-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_quizresults_question4'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentQuestion',
            field=models.IntegerField(default=0),
        ),
    ]
