# Generated by Django 3.1.1 on 2020-09-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_currentquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currentQuestion',
            field=models.IntegerField(default=1),
        ),
    ]
