# Generated by Django 3.1.1 on 2020-09-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200925_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='quizResults',
        ),
        migrations.AddField(
            model_name='user',
            name='question1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='question2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='question3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='question4',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
