# Generated by Django 3.1.1 on 2020-09-29 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200926_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
