# Generated by Django 3.1.1 on 2020-09-29 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_tracking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracking',
            new_name='LoginTracking',
        ),
    ]
