# Generated by Django 3.1.1 on 2020-09-29 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200929_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(max_length=364)),
                ('answer', models.CharField(max_length=364)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
